# Numpy

## How to import Numpy

In [2]:
import numpy as np

## Array

In [5]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[0])

[1 2 3 4]


### Creating Array

In [ ]:
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [13]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [14]:
np.arange(0,10,2)    #(start,stop,step)

array([0, 2, 4, 6, 8])

### Add, Remove, and Sort

In [ ]:
np.append()
np.delete()
np.sort()

In [24]:
ar = np.array([8,4,2,6])

In [25]:
np.append(ar, [1,2])

array([8, 4, 2, 6, 1, 2])

In [26]:
np.delete(ar, 1)

array([8, 2, 6])

In [27]:
np.sort(ar)

array([2, 4, 6, 8])

### Shape and Size

In [ ]:
ndarray.ndim()       #jumlah axes/dimensi array
ndarray.size()       #jumlah total elemen array
ndarray.shape()      #jumlah elemen yg disimpan di setiap dimensi array

In [28]:
array_example = np.array ([
    [[0,1,2,3],
    [4,5,6,7]],
    
    [[8,9,10,11],
    [12,13,14,15]]
])
print (array_example)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [30]:
array_example.ndim

3

In [31]:
array_example.size

16

In [32]:
array_example.shape    #(2,2,4) larik 2D dengan 2 baris dan 4 kolom

(2, 2, 4)

### Reshape

In [ ]:
np.reshape()

In [34]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [35]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [36]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

### Convert 1D to 2D

In [37]:
np.newaxis
np.expand_dims

#untuk meningkatkan dimensi array yg sudah ada

<function numpy.expand_dims(a, axis)>

In [38]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [40]:
#use np.newaxis to add a new axis
a2 = a [np.newaxis]
print(a2)
print(a2.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [41]:
#you can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [42]:
#for a column vector, you can insert an axis along the second dimension
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [43]:
#you can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [44]:
#you can add an axis at index position 0 with:

c=np.expand_dims(a, axis=0)
c.shape

(1, 6)

### Indexing and Slicing

In [45]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [48]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [54]:
five_up = (a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [55]:
#you can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [56]:
#you can select elements that satisfy two conditions using the & and | operators

c=a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


### Creating Array from Existing Data

In [ ]:
slicing indexing
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()

In [59]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [61]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [62]:
a_1=np.array([[1,1],
             [2,2]])
a_2=np.array([[3,3],
             [4,4]])

In [63]:
np.vstack((a_1, a_2))     #menumpuk vertikal

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [64]:
np.hstack((a_1, a_2))     #menumpuk horizontal

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [65]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
                    [13,14,15,16,17,18,19,20,21,22,23,24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [66]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [68]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
c = a.copy()
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Basic Array Operations

In [73]:
a = np.array([1,2,3,4])
a.sum()

10

In [77]:
b=np.array([[1,1], [2,2]])
print(b)
b.sum(axis=0)    #sum the columns

[[1 1]
 [2 2]]


array([3, 3])

In [78]:
b.sum(axis=1)    #sum the rows

array([2, 4])

In [80]:
data = np.array([1,2])
data

array([1, 2])

In [82]:
ones = np.ones(2)
ones

array([1., 1.])

In [84]:
print(data+ones)
print(data*data)
print(data/data)

[2. 3.]
[1 4]
[1. 1.]


### Broadcasting

In [85]:
data*2

array([2, 4])

### More Array Operations

In [ ]:
data.max()
data.min()
data.sum()

In [87]:
A = np.array([[4.9, 3, 6.3, 4.5],
             [3.2, 2.6, 8.9, 4.3]])
print(A)

[[4.9 3.  6.3 4.5]
 [3.2 2.6 8.9 4.3]]


In [88]:
A.sum()

37.7

In [89]:
A.min()

2.6

In [90]:
A.min(axis=0)

array([3.2, 2.6, 6.3, 4.3])

In [91]:
A.max()

8.9

In [92]:
A.max(axis=1)

array([6.3, 8.9])

In [93]:
A.std

<function ndarray.std>

## Matrices

### Creating Matrices

In [94]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [95]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.26309772, 0.35688874],
       [0.96422165, 0.80166298],
       [0.44454202, 0.64991626]])

In [96]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.1296631  0.02915697]
 [0.67388404 0.59249183]
 [0.57880256 0.74944593]]


### Matrix Arithmatic

In [97]:
data = np.array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [98]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [99]:
print(data+ones)

[[2. 3.]
 [4. 5.]]


In [100]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [102]:
print(data+ones_row)

[[2. 3.]
 [4. 5.]]


### Dot Product

In [105]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2=np.array([[7,8], [9,10], [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [106]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

### Matrix Indexing

In [107]:
data = np.array([[1,2], [3,4], [5,6]])

print(data)
print(data[0])
print(data[1])
print(data[0:1])
print(data[1:3])
print(data[0:2, 1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[[1 2]]
[[3 4]
 [5 6]]
[2 4]


### Matrix Aggregation

In [108]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [109]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [110]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


### Transposing and Reshaping

#### Transpose

In [111]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [112]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [115]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


#### Reshape

In [116]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [118]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


### N-Dimensional Array

In [119]:
ndarr = np.array([[[1,2], [3,4]],
                 [[5,6], [7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [120]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [121]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [122]:
print(np.random.random((4,3,2)))

[[[0.77656168 0.59374692]
  [0.63211661 0.04523162]
  [0.73569815 0.62021387]]

 [[0.14234115 0.15785011]
  [0.63991805 0.3662949 ]
  [0.53047445 0.83663035]]

 [[0.36314615 0.56032019]
  [0.52046907 0.48461979]
  [0.95146484 0.80538155]]

 [[0.01469483 0.98431605]
  [0.05453979 0.88072761]
  [0.74357228 0.65634785]]]


### Flatten N-Dimensional Array

In [123]:
arrflat = np.array ([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [124]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas

In [ ]:
error = (1/n) * np.sum(np.square(observed-prediction))